### ISSUE TITLE
Previews are always enabled on load when opacity is not default

### ISSUE THREAD

**Issue by via5** [acidbubbles/vam-collider-tuner#16]
Changing the preview opacity sets `showPreviews.val = true`, but this also happens on load, so previews are often enabled on scene load because I keep fiddling with the opacity. I don't know why this wasn't a problem before, nothing seems to have changed. I've commented out the statements here for now.

See

```
        JSONStorableFloat previewOpacity = new JSONStorableFloat("previewOpacity", ColliderPreviewConfig.DefaultPreviewsOpacity, value =>
        {
            if (!showPreviews.val) showPreviews.val = true;
```

and

```
        JSONStorableFloat selectedPreviewOpacity = new JSONStorableFloat("selectedPreviewOpacity", ColliderPreviewConfig.DefaultSelectedPreviewOpacity, value =>
        {
            if (!showPreviews.val) showPreviews.val = true;
```

**Comment by acidbubbles** [comment]
That should be an easy fix:

```c#
            if (!insideRestore) showPreviews.val = true;
```

Pushed, thanks for the helpful report! (If all open source issues were as good as yours, the world would be a better place!)
