### ISSUE TITLE
Feature: Mirror Left -> Right and Right -> Left Buttons

### ISSUE THREAD

**Issue by VamDazzler** [acidbubbles/vam-collider-tuner#5]
Should be pretty doable with a simple check for 'Left' and 'Right' on the collider names, and colliers appear to have correct quaternion setup such that positions already copy and paste nicely.

**Comment by acidbubbles** [comment]
I see what you mean, the only "difficult" thing is that colliders actually have conflicting names, I'm using their "order" to make them unique, I'm not sure this garantee will work for mirrorred colliders. If @ProjectCanyon comes up a new structure, it might be worth exploring.

**Comment by acidbubbles** [comment]
So now it should be possible. Technical notes:

1. When building the list of rigidbodies, colliders, auto-colliders and auto-collider groups, check if the first character of the name is "l" or "r". If so, try swapping the letter and check if there's a matching entry. Then keep that entry in the ModelBase, and if it exists, do two things:

1. Add a button to "go to mirror item"
2. Add a checkbox to "apply on mirror item" (or a button)

**Comment by acidbubbles** [comment]
There's a button in 2.0 to move from left to right, but no "sync" features.

**Comment by acidbubbles** [comment]
I'll close this and open another for syncing / copy paste.
