### ISSUE TITLE
Some presets don't load correctly

### ISSUE THREAD

**Issue by via5** [acidbubbles/vam-collider-tuner#9]
https://github.com/acidbubbles/vam-collider-editor/blob/master/src/Models/ModelBase.cs#L240

```
value.x = jsonClass["sizeX"].AsFloat;
value.y = jsonClass["sizeY"].AsFloat;
value.z = jsonClass["sizeZ"].AsFloat;
```

Should be `name*` instead of hardcoded strings.

**Comment by acidbubbles** [comment]
Good catch!
